[package]
name = "BrowserSelector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
const_format = "0.2.30"
json = "0.12.4"
winreg = "0.11.0"
